# Generated by Django 4.2.16 on 2025-03-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassroomStatus",
            fields=[
                (
                    "course_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="课程号"
                    ),
                ),
                (
                    "estimate",
                    models.CharField(blank=True, max_length=20, verbose_name="专注度评估"),
                ),
                ("dtime", models.DateTimeField(blank=True, verbose_name="评价时间")),
            ],
            options={"verbose_name": "课堂状态", "verbose_name_plural": "课堂状态",},
        ),
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, max_length=255, verbose_name="课程名称"),
                ),
                (
                    "class_name",
                    models.CharField(blank=True, max_length=30, verbose_name="课堂名称"),
                ),
                (
                    "teacher_name",
                    models.CharField(blank=True, max_length=20, verbose_name="授课教师"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="上课地址"),
                ),
                ("stage", models.IntegerField(blank=True, verbose_name="节数")),
                ("course_time", models.DateTimeField(blank=True, verbose_name="上课时间")),
            ],
            options={"verbose_name": "课程信息", "verbose_name_plural": "课程信息",},
        ),
        migrations.CreateModel(
            name="RecognitionResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("class_id", models.IntegerField(blank=True, verbose_name="课堂号")),
                (
                    "estimate",
                    models.CharField(blank=True, max_length=20, verbose_name="专注度评估"),
                ),
                ("dtime", models.DateTimeField(verbose_name="评价时间")),
                (
                    "rawpic",
                    models.CharField(blank=True, max_length=255, verbose_name="原始数据"),
                ),
                (
                    "resultpic",
                    models.CharField(blank=True, max_length=255, verbose_name="识别结果数据"),
                ),
            ],
            options={"verbose_name": "识别结果信息", "verbose_name_plural": "识别结果信息",},
        ),
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=30, verbose_name="教师姓名"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=2, verbose_name="性别"),
                ),
                (
                    "course",
                    models.CharField(blank=True, max_length=20, verbose_name="课程名称"),
                ),
                (
                    "post",
                    models.CharField(blank=True, max_length=20, verbose_name="职务"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=20, verbose_name="职称"),
                ),
                ("age", models.IntegerField(blank=True, verbose_name="年龄")),
                (
                    "education",
                    models.CharField(blank=True, max_length=255, verbose_name="教育程度"),
                ),
            ],
            options={"verbose_name": "教师信息", "verbose_name_plural": "教师信息",},
        ),
    ]
