# Generated by Django 4.2.16 on 2025-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, unique=True, verbose_name="手机号"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="默认用户名", max_length=50, verbose_name="账号"
                    ),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=128, verbose_name="密码"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("男", "男"), ("女", "女")],
                        default="男",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="未设置", max_length=128, verbose_name="邮箱"
                    ),
                ),
                (
                    "employeeId",
                    models.CharField(
                        blank=True, default="未设置", max_length=128, verbose_name="职工号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="未设置", max_length=128, verbose_name="地址"
                    ),
                ),
                (
                    "registrationTime",
                    models.DateTimeField(blank=True, verbose_name="注册时间"),
                ),
                (
                    "rawpic",
                    models.CharField(blank=True, max_length=255, verbose_name="头像"),
                ),
            ],
            options={"verbose_name": "用户", "verbose_name_plural": "用户管理",},
        ),
    ]
