# Generated by Django 4.2.16 on 2025-03-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_inf", "0002_alter_user_rawpic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rawpic",
            field=models.CharField(
                blank=True, default="/default.jpg", max_length=255, verbose_name="头像"
            ),
        ),
    ]
